name: check

on:
  pull_request:
  push:
    branches:
      - main
      - feat/shared-capabilities

jobs:
  cargo-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - name: Format check
        run: cargo fmt --all -- --check
      - name: Test workspace
        run: cargo test --workspace --all-features
